---
language: ruby
cache: bundler
rvm:
- 2.6.6
- 2.7.2
before_install: gem install bundler
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/537de1a350421f823aef
    on_success: change
    on_failure: always
    on_start: never
dist: bionic
