language: ruby
cache: bundler
rvm:
  - '2.3.4'
  - '2.4.1'
sudo: false
before_install: gem install bundler -v 1.13.0
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/537de1a350421f823aef
    on_success: change
    on_failure: always
    on_start: never